language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
addons:
  apt:
    packages:
      - bash
      - dash
      - ksh
      - zsh
      - tcsh
      - csh
      - fish
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - sudo apt-get update -qq
  - sudo apt-get install libdancer-perl libswitch-perl libfile-slurp-perl liblwp-protocol-psgi-perl cpanminus
  - sudo apt-get install libtime-piece-perl libjson-perl libplack-perl starman libcrypt-ssleay-perl 
  - sudo apt-get install libaudio-mpd-perl libnet-upnp-perl libpoe-component-client-mpd-perl
  - curl -L http://cpanmin.us | perl - --sudo Dancer2
  - cpanm Test::Pod # optional dependency
  - cpanm DateTime # optional dependency
install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org 
script: "start2.sh"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - domoticz@e-nef.com
  email:
    on_success: change
    on_failure: always
#env:
