language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.14"
addons:
  apt:
    packages:
      - bash
      - dash
      - ksh
      - zsh
      - tcsh
      - csh
      - fish
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - sudo apt-get update -qq
  - sudo apt-get install libdancer-perl libswitch-perl libfile-slurp-perl liblwp-protocol-psgi-perl cpanminus
  - sudo apt-get install libjson-perl libplack-perl libcrypt-ssleay-perl 
  - sudo apt-get install libaudio-mpd-perl libnet-upnp-perl libpoe-component-client-mpd-perl
  - sudo apt-get install starman
  - perlbrew install-cpanm -f
  - "cpanm -nq --installdeps --with-recommends --with-suggests ."
  - "cpanm Module::Install"
  - "cpanm Module::Install::XSUtil"
  - "cpanm Module::Install::ReadmeFromPod"
  - "cpanm JSON::XS"
  - "cpanm CBOR::XS"
  - "cpanm Sereal"
  - "cpanm Test::More"
  - "cpanm Test::Fatal"
  - "cpanm Test::Requires"
  - "cpanm Params::Coerce"
  - "cpanm Time::Piece"
  - "cpanm --verbose Time::Moment"
  #- curl -L http://cpanmin.us | perl - --sudo Dancer2
  - "cpanm Test::Pod # optional dependency"
env: RELEASE_TESTING=1 AUTOMATED_TESTING=1
install:
#- cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org 
#script: "exec ./MydomoAtHome/start2.sh"
script: plackup -E production -s Starman --workers=2 -p 5001 -a bin/app.pl
# branches:
#   only:
#     - master
notifications:
  recipients:
    - domoticz@e-nef.com
  email:
    on_success: change
    on_failure: always
#env:
#after_failure: "cat /home/travis/builds/npm-debug.log"
